version: '3'
services:
  iot-server:
    build: .
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=postgresql://postgres:H&ptiot2025@192.168.0.252:5432/iot?schema=public
      - PORT=3030
      - MQTT_HOST=broker.hivemq.com
      - MQTT_PORT=1883
    restart: always
